version: '3.4'

services:
  filemanagerservice:
    image: ${DOCKER_REGISTRY-}filemanagerservice
    build:
      context: .
      dockerfile: FileManagerService/Dockerfile
    depends_on:
      - rabbitmq
      - postgres
    volumes:
      - cs-storage:/app/storage
    ports:
      - "7000:80"

  archiveservice:
    image: ${DOCKER_REGISTRY-}archiveservice
    build:
      context: .
      dockerfile: ArchiveService/Dockerfile
    depends_on:
      - rabbitmq
    volumes:
      - cs-storage:/app/storage

  postgres:
    image: postgres:14-alpine
    volumes:
      - cs-postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "123passwd"
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    volumes:
      - cs-rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  cs-storage: {}
  cs-postgresql: {}
  cs-rabbitmq: {}
